apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: category-menu
  description: The Category Menu is a store component that displays a list of
    departments in a configurable menu layout. It helps organize and present
    categories and subcategories to improve navigation.
  tags:
    - typescript
    - react:16
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex-apps/category-menu
    vtex.com/platform-flow-id: ""
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: GZLLSZZ1
spec:
  system: store-framework-ui-apps
  lifecycle: stable
  owner: te-0013
  type: frontend-ui
  dependsOn: []
  subcomponentOf: store-framework
